### ISSUE TITLE
Hash / pound character (#) in password field truncates characters that follow

### ISSUE THREAD

**Issue by webcourse-ng** [laravel/lumen-framework#1099]
- Lumen Version: 7.2
- PHP Version: 7.3.11
- Database Driver & Version: MySQL 5.7.30

### Description:
Hash / pound character (#) in password field truncates characters that follow.

### Steps To Reproduce:
After following the example .env file, I inserted my password into the DB_PASSWORD line without quotes. It contained a # symbol. I started receiving 500 errors. I noticed in the error report that the password that was being actually passed ended where the first # symbol appeared.

Everything works if I put the password in quotes. Since the .env.example didn't use quotes, I followed its format.

**Comment by GrahamCampbell** [comment]
Yes, this is the expected behaviour, because a hash symbol is used to start a comment in a dotenv file. Please see https://github.com/vlucas/phpdotenv/tree/4.1#comments. There is an example here which shows this symbol is always treated as a comment start, even if the is content first and no whitespace: https://github.com/vlucas/phpdotenv/blob/4.1/tests/fixtures/env/commented.env#L10.
