### ISSUE TITLE
Laravel\Lumen\Routing\UrlGenerator should implement Illuminate\Contracts\Routing\UrlGenerator

### ISSUE THREAD

**Issue by cdarken** [laravel/lumen-framework#121]
Why isn't the class Laravel\Lumen\Routing\UrlGenerator implementing the interface Illuminate\Contracts\Routing\UrlGenerator like Illuminate\Routing\UrlGenerator does? I thought all Laravel was supposed to be built around contracts so things are easily interchangeable.

**Comment by lukasgeiter** [comment]
Lumens routing (and therefore also URL generating) is drastically different from Laravel. It is lighter and a lot faster. I'm guessing that's why it doesn't implement the Laravel contract. If you need a specific feature of Laravels route generator, chances are high that you actually should be using Laravel or doing things differently.

**Comment by cdarken** [comment]
Yeah, but I don't think that just implementing the interface would be such a big overhead, just provide dummy implementations for the not needed methods.

**Comment by lukasgeiter** [comment]
What's the point of implementing an interface if the methods are not going to work?

**Comment by cdarken** [comment]
You're right, the only two methods that are not present would be `action` and `setRootControllerNamespace` which until implemented (if ever) should throw an exception in case they are called.
The way I see it, a framework of this kind should be a base to build on, not just use it barebones. After all, by default it has views and controllers, using something like a minimal asset helper should be a minimal effort.

**Comment by cdarken** [comment]
Ok.
