### ISSUE TITLE
Unit testing Jobs using mock object always fails

### ISSUE THREAD

**Issue by rmblstrp** [laravel/lumen-framework#207]
Unit testing in Lumen to determine if a Job was dispatched always fails.  Live testing in Lumen shows the job to work as expected.  The unit test also works as expected when moved into a full instance of Laravel.

It appears that *app('Illuminate\Contracts\Bus\Dispatcher')* will return in instance of *Illuminate\Bus\Dispatcher* even though if you inspect *app()->instances* you can see *'Illuminate\Contracts\Bus\Dispatcher' => Mockery_0_Illuminate_Bus_Dispatcher*.  

Calling *app('Illuminate\Contracts\Bus\Dispatcher')* in a full Laravel instance will return *Mockery_0_Illuminate_Bus_Dispatcher* as expected.

**Error:**
Mockery\Exception\InvalidCountException: Method dispatch(object(Mockery\Matcher\Type)) from Mockery_0_Illuminate_Bus_Dispatcher should be called at least 1 times but called 0 times.

Job Example
```php
namespace App\Jobs;
class ExampleJob extends Job
{
    public function handle()
	{
	}
}
```

Unit Test Example
```php
class ExampleTest extends TestCase
{
    public function testBasicExample()
    {
        $this->expectsJobs(App\Jobs\ExampleJob::class);
		$job = new \App\Jobs\ExampleJob();
		app('Illuminate\Contracts\Bus\Dispatcher')->dispatch($job);
    }
}
```

**Comment by ariponce** [comment]
+1

**Comment by jessedc** [comment]
Lumen application's [overloaded `make()` implementation](https://github.com/laravel/lumen-framework/blob/5.1/src/Application.php#L425) is triggering `registerBusBindings()` and binding over the the previously bound mock form `expectsJobs()` in this case because the service binding has not been run prior to the call to `app()` after the mock is bound.

I'm unsure of the best solution, but removing the available binding for the Dispatcher prevents the behaviour:

```php
    public function testBasicExample()
    {
        unset ($this->app->availableBindings['Illuminate\Contracts\Bus\Dispatcher']);       
        $this->expectsJobs(App\Jobs\ExampleJob::class);
        $job = new \App\Jobs\ExampleJob();
        app('Illuminate\Contracts\Bus\Dispatcher')->dispatch($job);
    }
```
You can also trigger the registration prior to setting up the mock by just calling `app('Illuminate\Contracts\Bus\Dispatcher')` somewhere earlier in the test.

It feels like this may be more of a documentation issue since the registered bindings are a feature of Lumen.

**Comment by GrahamCampbell** [comment]
Feel free to discuss on the forums.

**Comment by bkuhl** [comment]
This is very unexpected behavior.  I just battled this for quite some time.  Having to unset the IOC binding feels like hacky code to work around a bug.

It seems like this issue was closed without giving it any consideration.

**Comment by Olofguard** [comment]
@jessedc Been spinning my wheels on this as well. Thanks for the solution. 

Though I agree with @bkuhl this does seem a bit hacky.

**Comment by loicm** [comment]
I ran into the same bug while using `expectJobs()` in a test with a fresh Lumen application.

I don't understand why this bug is closed.

```bash
$ composer show -i
laravel/lumen-framework           v5.2.7
mockery/mockery                   0.9.5
```
