### ISSUE TITLE
Missing /app/storage/framework/* directories causes error with blade compilation

### ISSUE THREAD

**Issue by swvjeff** [laravel/lumen-framework#247]
I just tried creating a blade view out of the box and got a file_put_contents() error. The /app/storage/framework/views directory was missing (along with cache and sessions), which caused $this->cachePath to be set to false in BladeCompiler::compile(). The compile() method checks for *null* but not false. Once I created the "/app/storage/framework/views" directory the error went away.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/lumen/tree/master/storage/framework/views

**Comment by GrahamCampbell** [comment]
Not missing.

**Comment by swvjeff** [comment]
Uhhh weird, no clue why I don't have them. Thanks

**Comment by lukeed** [comment]
Just to note: 

I installed Lumen 5.2 when it first released (no view support). 
Since then, view support was added back in, so I received this error. 

Just in case anyone else stumbles across this, manually add the directories `storage/framework/views` ... or make sure your `view.compiled` config value exists.

**Comment by georgexsh** [comment]
what a surprise that lumen wont create those directories while it has write permission.
