### ISSUE TITLE
Class Crypt not found

### ISSUE THREAD

**Issue by syropian** [laravel/lumen-framework#307]
In my User model I added 

```
use Crypt;
```

at the top, and then created a setter like so:

```
public function setPasswordAttribute($value){
    $this->attributes['password'] = Crypt::encrypt($value);
}
```

but it always throws `Fatal error: Class 'Crypt' not found`.

**Comment by GrahamCampbell** [comment]
illuminate/support/facades/crypt

**Comment by syropian** [comment]
The docs fail to mention any of this

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/lumen-framework/blob/5.2/src/Application.php#L567

**Comment by GrahamCampbell** [comment]
in 5.2, those are the only **aliases** we register.

**Comment by syropian** [comment]
@GrahamCampbell Thanks, looks like it's working now that I manually added it as a class alias.

**Comment by GrahamCampbell** [comment]
I'd still recommend you don't do this and just import the actual class instead of an alias.

**Comment by GrahamCampbell** [comment]
I personally hate aliases and think they should be removed from the core, but not everyone agrees with me. TBH, there are probably more people that disagree.

**Comment by syropian** [comment]
@GrahamCampbell Yeah, the real issue was is the documentation for Encryption, which makes it look as though that `Crypt` facade is already accessible. *shrugs*

**Comment by j3j5** [comment]
I know this is closed but the documentation is still broken, is there a way to make a PR for the docs? Because they are still broken and I think we shouldn't have to come to the closed issues of the framework to find out what's failing.

I'm happy to make the PR to fix this, either fixing the docs or adding the proper `class_alias` call on the application although from what I see, the first option is the preferred one.

**Comment by MouadZIANI** [comment]
There's any alternative of Crypt in laravel 7 ?
