### ISSUE TITLE
method='put',$request->has();do not work

### ISSUE THREAD

**Issue by liuzhaowei55** [laravel/lumen-framework#377]
if `method='put'` and the request data in the HTTP body not in HTTP URL, the `$request->has()` do not work.

**Comment by liuzhaowei55** [comment]
When I edit the request header `content-type:application/x-www-form-urlencoded` I can get the request data,so if I want to upload picture I can use `method=post` only.

**Comment by atapatel** [comment]
I also found this issue

**Comment by yuloh** [comment]
What `Content-Type` are you sending when it doesn't work?  You need to set either `application/x-www-form-urlencoded`, `application/json`, or a json vendor extension like `application/vnd.api+json` or the request body will not be checked.

I added a test case [here](https://github.com/laravel/lumen-framework/compare/5.2...yuloh:check-put-request-has) to check if it worked.

Note that `Request@get` will not work with JSON payloads since that method is on the Symfony HttpFoundation class, which does not parse JSON payloads.

**Comment by GrahamCampbell** [comment]
Not intended to work for the same reason as https://github.com/laravel/lumen-framework/issues/400.

**Comment by liuzhaowei55** [comment]
@yuloh When `method`=`put` and `Content-Type: multipart/form-data; boundary=__X_PAW_BOUNDARY__`,if I upload a picture ,then I use the function `$request->hasFile()` ,it doesn't work.
