### ISSUE TITLE
ServiceProvider::boot() always called after ServiceProvider::register() 

### ISSUE THREAD

**Issue by chapsuk** [laravel/lumen-framework#399]
What's wrong, [this documentation](https://github.com/laravel/lumen-docs/blob/5.2/providers.md#the-boot-method)  or [this realisation](https://github.com/laravel/lumen-framework/blob/5.2/src/Application.php#L171-L172) ?

**Comment by djtarazona** [comment]
Curious about this as well @taylorotwell. Looks like deferred service providers are not supported as well?

**Comment by chapsuk** [comment]
Could you please attach a comment? why this issue is closed

**Comment by GrahamCampbell** [comment]
The docs are correct, and the code is correct also.

**Comment by GrahamCampbell** [comment]
When you call register, boot is run after all other providers registered before hand.

**Comment by GrahamCampbell** [comment]
If you're wanting lots of complex service providers, just use laravel for a more complete service provider implementation.

**Comment by djtarazona** [comment]
> When you call register, boot is run after all other providers registered before hand.

You may be correct when you say "before hand."  However, the documentation implies that `boot` is called after all providers have been registered, regardless of the order you registered them.

For example, if I had the following code.

```php
$app->register(App\Providers\EventServiceProvider::class);
$app->register(App\Providers\AppServiceProvider::class);
$app->register(App\Providers\AuthServiceProvider::class);
```

I'd expect my `EventServiceProvider`'s `boot` method to be called after `AppServiceProvider` and `AuthServiceProvider` had been registered.  Instead, `EventServiceProvider` is registered and it's `boot` method is immediately called before `AppServiceProvider` and `AuthServiceProvider` are registered.  Because [`boot` is called immediately after `register`](https://github.com/laravel/lumen-framework/blob/5.2/src/Application.php#L171-L172), what is the point of the `boot` method?  All that code could just be placed in the `register` method.

**Comment by GrahamCampbell** [comment]
> what is the point of the boot method

There are other ways to load service provider, like how lumen loads the laravel ones internally.

**Comment by Poolshark** [comment]
Sorry, I don't get that. Can you explain what @djtarazona had pointed out? What is the point of having a `boot` method?
