### ISSUE TITLE
X-HTTP-Method-Override doesn't work

### ISSUE THREAD

**Issue by phuib** [laravel/lumen-framework#400]
A patch route, like below, will not work when using POST with a header X-HTTP-Method-Override: PATCH
```php
$app->patch('/foo', function () use ($app) {
    return 'bar';
});
```

The request throws a 405 MethodNotAllowedHttpException.

```
POST /foo HTTP/1.1
X-HTTP-Method-Override: PATCH
```

**Comment by crynobone** [comment]
Any reason not to use `PATCH /foo` directly? 

The http method override is handled by Symfony, not Illuminate.

**Comment by GrahamCampbell** [comment]
This won't work in Lumen, unless we actually creates a response object. Normally we don't to save time.

**Comment by phuib** [comment]
I noticed this problem when I was considering using Lumen for a jsonapi compliant project. Laravel handles these requests fine, so I didn't understand why Lumen wouldn't.

**Comment by GrahamCampbell** [comment]
> so I didn't understand why Lumen wouldn't.

I'm not being funny, but if you read the source code, it'll become immediately obvious why, and I've already explained why anyway:

> This won't work in Lumen, unless we actually create a response object. Normally we don't to save time.

### Summary:

**This is not supported by Lumen out of the box. If you want all this jazz, just use Laravel.***

**Comment by linuxjuggler** [comment]
@GrahamCampbell but the [docs](https://lumen.laravel.com/docs/5.4/requests) clearly state that it's supported out of the box

> Using a few simple methods, you may access all user input from your Illuminate\Http\Request instance. You do not need to worry about the HTTP verb used for the request, as input is accessed in the same way for all verbs

or there is something we are missing from the docs.

Thanks

**Comment by GrahamCampbell** [comment]
> @GrahamCampbell but the docs clearly state that it's supported out of the box

The docs do not say that header is supported, they only say that "input is accessed in the same way for all verbs".

**Comment by linuxjuggler** [comment]
Thank @GrahamCampbell  for the reply, but am lost here, so Patch/Put are not supported because they are depending on the headers?

Today I was working on a small project, using the Latest Lumen code, and using this small code in the tests

```
$this->put('/',["options" => "1234"]);
```

and in my controller I had:
```
$options = $request->all();
```

and the result was an empty array.

and even when I used PUT in Postman with `form-data` I didn't get anything, the only way I was able to send data was to change from `form-data` to `x-www-form-urlencoded` which is not going to work if am going to upload a file.

The only trick that got me to solve this issue is to send my request in my test using `$this->json` so why `PUT` verb is not treated like any other verbs? or Lumen support only GET/POST?

and if we need to update a record we should forget everything about REST and use POST not PUT?

am just trying to find a solution to the problem.

thanks again for taking the time to reply

**Comment by GrahamCampbell** [comment]
> Thanks @GrahamCampbell for the reply, but am lost here, so Patch/Put are not supported because they are depending on the headers?

They are supported. You just need to actually send those requests, instead of faking them with a header.

**Comment by linuxjuggler** [comment]
@GrahamCampbell as I said in my example I didnt fake them, unless in tests when I request `$this->put` am faking a request? is that what you mean?

thanks

**Comment by linuxjuggler** [comment]
@GrahamCampbell this video show exactly what am doing, and how am not faking any request via Postman, and how the Controller won't populate the data https://www.youtube.com/watch?v=SvvQ_YhU8JA

Thanks again Graham for your help in advance

**Comment by mstaack** [comment]
@linuxjuggler just go with json and type raw in postman.. then add your json content for the request..works for me

**Comment by linuxjuggler** [comment]
@mstaack thanks for the reply, but I don't think this is the normal way to do it, I mean clearly there is something missing here, let's say you want to upload a file when you edit the record since at the end PUT will be used for updating the data, the raw won't work.

I do know that for example if you changed the type to `x-www-form-urlencoded` it will work as I mentioned in my previous comment, but again this will not help if you wanted to upload a file.

**Comment by linuxjuggler** [comment]
sorry @GrahamCampbell its look like Postman caused the issue, and I test it with other clients and it worked.

its look like we do need to check and be careful cause even `$this->put` in the tests does not send the correct headers. which is something I'll look into more.

sorry again for bothering you, and thanks for your help

**Comment by madhurbhaiya** [comment]
Just for Info, X-HTTP-Method-Override does work since changed done here: https://github.com/laravel/lumen-framework/commit/83fd12f4bc5ca9d8bc16ec341838e5086edf4c0c

```Request::capture()``` method of Illuminate/Request now enables the **httpMethodOverride** paramter. 

Ref:  https://github.com/laravel/framework/blob/f55fee2a6333a6224a258827eda55b32d64b112a/src/Illuminate/Http/Request.php#L62


Not sure, if this was intended for Lumen or not, because it does open a security concern.
