### ISSUE TITLE
Middleware closure may not be defined.

### ISSUE THREAD

**Issue by caffeineinc** [laravel/lumen-framework#477]
Closure in some instances can be undefined, such as when a route is using the string based reference with middleware:

``` php
$app->get('/url/to/{string}', [
    // Route specific middleware.
    'middleware' => 'MyMiddleWare',
    'MySpecialController@myAction'
]);
```

Since closure isn't instantiated or defined in the normal way, the variable is not set, which crashes the on this route.

https://github.com/laravel/lumen-framework/blob/5.3/src/Concerns/RoutesRequests.php#L523

**Comment by caffeineinc** [comment]
Does lumen have active development I wonder? Middleware is pretty important, but I have no idea if doing a pull request will ever get merged :/

**Comment by david-robinson-practiceweb** [comment]
I know this is well over a year old but if anyone else hits the same issue the fix for this is that you have to use 'uses' for the string reference once you start using other route options.
See the example at [https://lumen.laravel.com/docs/5.6/controllers#controller-middleware](https://lumen.laravel.com/docs/5.6/controllers#controller-middleware)
`$router->get('profile', [
    'middleware' => 'auth',
    'uses' => 'UserController@showProfile'
]);`

**Comment by chandru89new** [comment]
Thanks for this.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
