### ISSUE TITLE
PSR-7 support in ProvidesConvenienceMethods::validate()

### ISSUE THREAD

**Issue by MageLuingil** [laravel/lumen-framework#493]
I'm using the `symfony/psr-http-message-bridge` to add PSR-7 support to my Lumen 5.3 app (as per [the docs](https://lumen.laravel.com/docs/5.3/requests#psr7-requests)).  PSR-7 requests work fine in my controllers, but I cannot call `$this->validate()` using the PSR request object.

The problem is in the definition of the `ProvidesConvenienceMethods::validate()` method: the typehint is hardcoded to require an `Illuminate\Http\Request` object, so passing a `Psr\Http\Message\ServerRequestInterface` throws an error.

This issue is similar to (but not the same as) #487, but could have the same solution:

> the other option is to contribute to illuminate\http making all request compliant to the psr-7 standard which is what "you should do".
> 
> Is there any roadmap to implement the psr-7 standard

**Comment by jkirkby91-2** [comment]
The illuminate\Http depends on symfony\Http-Kernel which doesn't support PSR7 yet. You would first need to get the core symfony component on a PSR7 road map to then get the illumate http package to be on that same path, which i think will be a long time coming.

I tried using the message bridge and it doesnt provide true psr-7. so i created an adapter middleware that does

https://github.com/jkirkby91-2/IlluminateRequestPSR7Adapter 

register the service provider and then in your routes do something like

$app->group(['middleware' => ['before' => 'psr7adapter', 'after' => 'apiarchitect.auth']], function () use ($app)
{
    global $app;

    $app->post('search', 'App\Http\Controllers\SearchController@search');

});

This done and said it still makes it incompatible with any type hinted function for illuminate\request, since i had to write a custom validation method for validating against laraveldoctrine it didnt really matter to me

**Comment by driesvints** [comment]
Yeah, I think this can't be solved until Request would implement `Psr\Http\Message\ServerRequestInterface` but I doubt that will happen any time soon. Try to start a discussion about it in https://github.com/laravel/ideas to see if there's any interest.
