### ISSUE TITLE
[5.4] After middleware doesn't works when an exception is thrown

### ISSUE THREAD

**Issue by abellion** [laravel/lumen-framework#553]
https://github.com/laravel/framework/issues/17542

- Laravel Version: 5.4
- PHP Version: 7.0

### Description:

When an exception is thrown during the request processing (i.e. in controllers, or by the router) the middleware ```handle``` method is aborted ; what's after the ```$next``` closure call is never executed. 

It worked well in 5.3.

**Comment by taylorotwell** [comment]
Can you provide an example that I can recreate?

**Comment by abellion** [comment]
Yeah, here is a repo with the issue : https://github.com/abellion/lumen-middleware-issue

This is a fresh install of lumen 5.4, I juste added a header to the response from the ```ExampleMiddleware``` class.

**Comment by liugj** [comment]
please edit src/Routing/Pipeline.php  (5.4) line 25  line 30 rename  getSlice to carry
and line  48 rename  function getInitialSlice to prepareDestination
because in illuminate/pipeline/Pipeline.php (v5.4)  `function getSlice`  was renamed carry and `function getInitialSlice`  has rename  prepareDestination
