### ISSUE TITLE
Trailing slash in URL for POST method causes error

### ISSUE THREAD

**Issue by michael-erwin** [laravel/lumen-framework#654]
- Lumen Version: 5.5.0
- PHP Version: 7.1.1
- Database Driver & Version: MariaDB 10.1.21

### Description:
When sending POST request to URL with additional slash added at end the response results to "405 Method Not Allowed".

### Steps To Reproduce:

1. Make a route for POST.
Example:
```
$router->post('/test', function () {
    return "POST request detected.";
});
```
2. Send a POST request to the route with additional slash at the end.
Example:
```
http://api.blog.local/v1/test/
```

**Comment by hakuno** [comment]
Read the HTTP specs, the correct is:

> http://api.blog.local/v1/test

**Comment by michael-erwin** [comment]
I don't think so. HTTP specs has nothing to do with it. It's more on how you would interpret a RESTful resource. Have a look 

[REST for Web Services](https://en.wikipedia.org/wiki/Representational_state_transfer#Applied_to_Web_services)

Trailing slash only means "collection". 

POST http://api.blog.local/posts/ -> means create an element(s) to a collection

I mentioned POST specifically because the rest of the verbs works as expected.

**Comment by humbertowoody** [comment]
I'm currently experiencing the same issue. The weird thing about this is that the trailing `/` is actually non-problematic on previous versions of Laravel, maybe it's some issue on 5.5+. Actually what @michael-erwin is pointing out is true since some browsers add trailing characters and it shouldn't affect endpoints on an API or some other Web Services. Ultimately, a rewrite directive on the Apache/Nginx configuration should do the trick (or not?).

**Comment by snuggs** [comment]
@michael-erwin REST has nothing to do with this as well. from a URI perspective a trailing slash to a collection is about as relevant as a path to a bonafied file. COULD be but not necessarily (nor is this defined). I feel a little tangental however your concern is valid. Just stumbled across this when researching the very same topic in another ecosystem.I know the specs like the back of my hand but Laravel not so much. Assuming [Ockham's Razor](https://en.wikipedia.org/wiki/Occam%27s_razor) in effect i'd assume any route to `/test` to only be able to route to `/test` unless explicitly stated not to. From the canonical URL spec `/foo` and `/foo/` are two totally different resources. A redirection which is commonplace is merely a convention that developed from the web. Google would also treat these as different endpoints as well depending on canonical strategies (e.g. `301` status code or `<link rel=canonical>`)

**Comment by snuggs** [comment]
After speaking with some spec members @humbertowoody the browser adds a `/` for root domain addresses. anything else typically they shouldn't. `example.com` would need some path to send to the server in the HTTP request. `GET /` this is where the `example.com/` comes from. `GET /foo` is totally valid path so the server would receive `/foo` not `/foo/`

Does this make sense?

**Comment by driesvints** [comment]
This works for me. Try updating to the latest version.

**Comment by ramsesmoreno** [comment]
It may be also something related to the web server, because in my case, it works both ways locally and the same script sends an error on production if called with a trailing slash.

**Comment by Arthur-Kamau** [comment]
Is there i way i could fix this issue in the server,
as the application has already been pushed into production

**Comment by aduuna** [comment]
In web.php
```
Route::post('/comments', 'CommentController@store')
```
In views/comments/create.blade.php
`<form action="/comments/" method="POST">`

This works fine when serving locally with ` $ php artisan serve `  in version 5.8.28 (latest)

But fails in production with Apache or NGINX server

####My Advice
Instead of hard-coding the resources, You should use resource/route names. In that case, you never have to remember if your server will trim/append a trailing slash.

In web.php
```
Route::post('/comments', 'CommentController@store')->name('comments.store')
```
In views/comments/create.blade.php
`<form action="{{ route('comments.store') }}" method="POST">`

[Read more on url generation here](https://laravel.com/docs/5.8/urls)
