### ISSUE TITLE
Driver [] is not supported  Storage::disk

### ISSUE THREAD

**Issue by alexisaraya** [laravel/lumen-framework#659]
- Lumen Version: 5.5
- PHP Version: 7.0
- Database Driver & Version:

### Description:

lumen.ERROR: InvalidArgumentException: Driver [] is not supported. in /var/www/html/vendor/illuminate/filesystem/FilesystemManager.php:124

### Steps To Reproduce:

boopstrap\app.php

`$app->singleton(
    Illuminate\Contracts\Filesystem\Factory::class,
    function ($app) {
        return new Illuminate\Filesystem\FilesystemManager($app);
    }
);`

in customController.php

`use Illuminate\Support\Facades\Storage;
class MessageController extends Controller
{
Storage::disk('local')->put('file.txt', 'Contents');
}
`

**Comment by deividaspetraitis** [comment]
Hello @alexisaraya it is missing feature rather than a bug. In your case you forgot just add dependency for `filesystem` local driver. Running following command should be enough to solve your problem: `composer require league/flysystem`. In case there will be some more issues you can follow my 
short "how to"guide: https://gist.github.com/deividaspetraitis/4cca4fa6a61cc9a75e12f640041e53f5
Hope it helps!

**Comment by mancarv** [comment]
I has this same issue, It was missing `$app->configure('filesystems');` in boopstrap\app.php

**Comment by prog-24** [comment]
This is still an ongoing issue and it might be related to this line.

    $this->app->singleton('filesystem.disk', function () {
            return $this->app['filesystem']->disk($this->getDefaultDriver());
        });

        $this->app->singleton('filesystem.cloud', function () {
            return $this->app['filesystem']->disk($this->getCloudDriver());
        });`

I noticed that get default driver is never called.

**Comment by prog-24** [comment]
I figured out the offending line. Either extend a new facade so the facade accessor is filesystem.disk or extend a new service provider from the default filesystem service provider and change how it works so it is not looking for filesytem.cloud or filesystem.disk alone.

**Comment by alexisaraya** [comment]
Tranks for your comments and help

**Comment by Rijen** [comment]
I had this same issue, and i miss "s" letter in config file name.. "filesystem.php"

_It  problem only in loading config._ 
_if you lose flysystem, you see error "Class 'League\Flysystem\Adapter\Local' not found" (@deividaspetraitis)_


-  in bootstap/app.php must be string `$app->configure('filesystems');`
-  file placed 'config/filesystems.php' with next minimum content:

```
<?php

return [
    'default' => env('FILESYSTEM_DRIVER', 'local'),
    'disks' => [
	'local' => [
	    'driver' => 'local',
	    'root' => storage_path('app'),
	],
    ],
];
```



<details>
  <summary>How it works?</summary>
  
See file vendor/illuminate/Filesystem/FilesystemManager.php
in function `resolve` throw error with $config['driver']. We see this empty, it means the problem is in the config
```
    protected function resolve($name)
    {
        $config = $this->getConfig($name);

        if (isset($this->customCreators[$config['driver']])) {
            return $this->callCustomCreator($config);
        }

        $driverMethod = 'create'.ucfirst($config['driver']).'Driver';

        if (method_exists($this, $driverMethod)) {
            return $this->{$driverMethod}($config);
        } else {
            throw new InvalidArgumentException("Driver [{$config['driver']}] is not supported.");
        }
    }
```
see getConfig fn..

```
    protected function getConfig($name)
    {
        return $this->app['config']["filesystems.disks.{$name}"];
    }

```

we need have file named `config/filesystems.php`, with block `disks`, with not empty parameter `driver`

</details>
