### ISSUE TITLE
custom from email Id not used by lumen 

### ISSUE THREAD

**Issue by sachinsts** [laravel/lumen-framework#684]
- Lumen Version: 5.4.7
- PHP Version:7.0.22
- Database Driver & Version:

### Description:
every time default  from mail Id used by lumen instead of using parameter passed in mail function,
$user_data['mail_from'] = $_ENV['MY_CUSTOM_EMAIL_ID'];
$user_data['mail_from_name'] = $_ENV['CUSTO_MAIL_FROM_NAME'];
$user_data['email_to'] = 'test@yopmail.com';
$user_data['mail_subject'] = "test";
  Mail::send('Mailtranscript.email', $user_data, function ($message_body) use ($user_data) {
      $message_body->from($user_data['mail_from'], $user_data['mail_from_name']);
      $message_body->to($user_data['email_to']);
      $message_body->subject($user_data['mail_subject']);
    });

**Comment by hakuno** [comment]
@sachinv2 

Debug the `$user_data['mail_from']` array element with `dd ` function and you will see that.

Because I'm unsure about your `$_ENV['MY_CUSTOM_EMAIL_ID']` use. You might use `env` function instead of. For instance, see below


`$user_data['mail_from'] = env('MY_CUSTOM_EMAIL_ID', 'default@mail.com');`


Maybe you'll get it working at this way. Check it out...

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
