### ISSUE TITLE
Can not schedule queue jobs

### ISSUE THREAD

**Issue by Korri** [laravel/lumen-framework#733]
- Lumen Version: 5.6.1
- PHP Version: 7.1, 7.2

### Description:
Queuing jobs in Lumen throws error `Call to a member function onQueue() on integer` but the job is still queued.

If the job does not implement `ShouldQueue`, it's worse as the Scheduler is trying to call `dispatch_now()` which does not exists on Lumen:
`Call to undefined function Illuminate\Console\Scheduling\dispatch_now()`

### Steps To Reproduce:
1. Queue a job that implements `Illuminate\Contracts\Queue\ShouldQueue` for example:
```php
$schedule->job(new ExampleJob())->everyMinute();
```
2. Run it using `php artisan schedule:run`

Example repository: https://github.com/Korri/lumen-schedule-job/commit/ab64a7b0d5036d8caaf4c99d2beab7e7ffdd78f3

**Comment by emil-nasso** [comment]
I experienced this problem too. It can be worked around by dispatching jobs like this:

```php
        $schedule->call(function () {
            $job = (new HelloWorldJob())->onQueue('cron');
            dispatch($job);
        }
        )->description("hello world")->everyMinute();
```

The problem seems to be that there is a difference between the `dispatch` helper in laravel and lumen. The laravel variant returns an object but the lumen on doesn't. 

This is the line causing it: https://github.com/illuminate/console/blob/master/Scheduling/Schedule.php#L99

If you call `onQueue` on the job instead of on the result of `dispatch` it seem to work in lumen.

**Comment by richardbporter** [comment]
I'm having this issue as well. Any plans on fixing this for Lumen?

**Comment by simonhamp** [comment]
You can make a job non-queueable without causing problems if you add the [`dispatch_now` method from Laravel](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/helpers.php#L396-L408) to your global namespace somehow. (I personally prefer to create a `helpers.php`, put this chunk in there and autoload it via my `composer.json`). This should really be in Lumen's `helpers.php`.

To stop the error appearing on the queued jobs is a bit more complicated. In Laravel, `dispatch` proxies jobs through a [`PendingDispatch` class](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Bus/PendingDispatch.php) which is what would be returned from the `dispatch` helper. But it's not available in Lumen because `Illuminate\Foundation` isn't available as a subtree split.

I'm not clear why this class is in `Illuminate\Foundation` and not in [`Illuminate\Bus`](https://github.com/illuminate/bus) (where it would make more sense IMHO). If it was in `Illuminate\Bus` then `dispatch` in Lumen could match its Laravel counterpart and the world would be right again.

**Comment by driesvints** [comment]
This is indeed a bug which should be fixed. Welcoming PR's for this. Short term solution is probably to add a `dispatch_now` helper to the Lumen `helpers.php` file.

**Comment by simonhamp** [comment]
@driesvints not sure if a single PR can cover this... it really feels like `Illuminate\Foundation` needs to be available to Lumen or `PendingDispatch` moves to `Illuminate\Bus`, but I guess the implications of both of those solutions are further reaching than I'm aware of.

**Comment by JacksonIV** [comment]
I made a PR to make the scheduler compatible with Lumen.

**Comment by driesvints** [comment]
Thanks @JacksonIV!

**Comment by simonorups** [comment]
I had the same issue in lumen 8.x today. I was queuing using  `dispatch(new ExampleJob);` so after spending some good time googling with no success, I decided to replaced `dispatch(new ExampleJob);` with`Queue::push(new ExampleJob);` and added `use Illuminate\Support\Facades\Queue;` at the top then jobs started queuing fine. For more details refer to [](https://lumen.laravel.com/docs/8.x/queues) Dispatching Jobs section
