### ISSUE TITLE
url() helper generates wrong URLs when queue is used

### ISSUE THREAD

**Issue by chimit** [laravel/lumen-framework#791]
- Lumen Version: 5.6.4
- PHP Version: 7.2
- Database Driver & Version: MySQL 5.7

### Description:
I'm using Mail Notifications. When I set `QUEUE_DRIVER=sync` in my `.env` file everything is OK:

![image](https://user-images.githubusercontent.com/839349/42445685-72b1115c-83a6-11e8-8a67-0558bce22467.png)

But if I change the queue driver to `database` and run `php artisan queue:work` I receive a wrong URL:

![image](https://user-images.githubusercontent.com/839349/42445748-ae88b4c8-83a6-11e8-9bd7-f5d96281eb19.png)

The problem may be related to this issue: https://github.com/laravel/framework/issues/14139

### Steps To Reproduce:
`.env`
```
APP_URL=http://mysite.local
QUEUE_DRIVER=database
```

`config/app.php`
```php
<?php

return [
    'name' => env('APP_NAME', 'Lumen'),
    'url' => env('APP_URL', 'http://localhost'),
];
```

`app/Notifications/UserCreated.php`
```php
...

public function toMail($notifiable)
{
    return (new MailMessage)
                ->subject('Confirm your email address')
                ->line('Please, confirm your email address by clicking the button below:')
                ->action('Confirm email', url('confirm?token=' . $notifiable->verification_token))
                ->line('Thank you for using our application!');
}

...
```

**Comment by JacksonIV** [comment]
The fix, you referenced in the issue, is implemented in Lumen. You can find it in the `setRequestForConsole` method on line 70 in `Laravel\Lumen\Console\Kernel`.

However, in the constructor of the same class, a conditional is defined which checks whether the `Request` has already been bound in the container. If this is the case, the `setRequestForConsole` will be called.

In the `Application` class, located in the Lumen framework, the request method will be bound on every request, no matter if you're running in the console or not. That's why the  `setRequestForConsole` method will never get called.

**Comment by driesvints** [comment]
Seems like this was fixed now. Thanks!
