### ISSUE TITLE
Call to undefined function dd()

### ISSUE THREAD

**Issue by moeen-basra** [laravel/lumen-framework#820]
- Lumen Version: 5.7.*
- PHP Version: 7.2.10
- Database Driver & Version:
MySQL 5.6
### Description:
After upgrading lumen 5.6 to 5.7 its starts complaining about dd function not found.

### Steps To Reproduce:
use dd any where in the applicatoin.

**Comment by JacksonIV** [comment]
The ‘dd’ helper was removed from the illuminate/support package in 5.7. I think it’s because symfony’s var dumper now ships with laravel by default, which contains ‘dd’ and ‘dump’. 

So, if you’d like to include Symfony’s var dumper, you may include the package through composer:

`composer require symfony/var-dumper`
