### ISSUE TITLE
Uncaught ReflectionException: Class path.storage does not exist

### ISSUE THREAD

**Issue by andrewgorpenko** [laravel/lumen-framework#870]
- Lumen Version: 5.7.7
- PHP Version: 7.2
- Database Driver & Version: does not matter

### Description:
The old error appeared again. I saw dozens of related issues about this problem and I am surprised that it is still not fixed. No external packages installed. Deleted composer.lock and vendor folder, ran `composer install` command and app successfully crashed.

### Steps To Reproduce:
I feel you could not reproduce this, but here is what I did today:
- removed composer.lock and vendor folder.
- ran `composer install`
- TADAA

**Comment by andrewgorpenko** [comment]
Oh ya, I've just noticed that it installs Laravel's framework sometimes. In one project's copy it Composer says `Nothing to install`. But when I do those steps (see **Steps To Reproduce section**) it installs framework alongside Lumen. Why God...

**Comment by driesvints** [comment]
I can install and run a vanilla Lumen just fine. Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by HenkPoley** [comment]
This happens when something requires `laravel/framework`. Which will then gain priority over lumen, trough its 'replaces' listing: https://packagist.org/packages/laravel/framework 

Composer compares with composer.lock to minimize the amount of changed packages. So just removing the offending dependency from `composer.json` is not enough. You also need to run `rm -rf vendor composer.lock && composer install`
