### ISSUE TITLE
gRPC support

### ISSUE THREAD

**Issue by payalord** [laravel/lumen-framework#874]
- Lumen Version: 5.7.7
- PHP Version: 5.5 and higher or 7 and higher
- Database Driver & Version: MySQL 5.6

### Description:
Add gRPC support and option to use it instead of Http. More info here https://grpc.io/ and here https://grpc.io/docs/quickstart/php.html

### Steps To Reproduce:
Enhancement

**Comment by yuloh** [comment]
Unfortunately it [isn't currently possible](https://github.com/grpc/grpc/issues/11683#issuecomment-313016376) to create gPRC servers in PHP.  It would also be a very different framework since the bulk of Lumen is built around HTTP 😀.

Generally feature requests should be posted here instead: https://github.com/laravel/ideas/issues.  See the [contribution guide](https://laravel.com/docs/5.7/contributions#core-development-discussion) for more info.

**Comment by driesvints** [comment]
We currently have no intention to support gPRC in Lumen. If you like to see this in Lumen it's indeed best to post to the ideas repo like @yuloh suggested.

**Comment by payalord** [comment]
Ok thanks guys. I'll post there then with explanation of reasons why it will benefit Lumen and maybe with ideas on how even possible to do this.
